# Generated by Django 4.0.3 on 2022-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cows',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('collar_id', models.CharField(max_length=10, unique=True)),
                ('cow_number', models.CharField(max_length=30)),
                ('collar_status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cows',
            },
        ),
    ]
